
package presentacion;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventanas.ConsultaCliente;
import ventanas.ConsultaLibro;
import ventanas.DarAlta;
import ventanas.Fidelizacion;
import ventanas.InicioSesionAlta;
import ventanas.InicioSesionInformes;
import ventanas.PedidosPendientes;
import ventanas.Principal;

/**
 *
 * @author Gisela, Elia y Achraf
 */
public class Inicio extends javax.swing.JFrame {
    
    private String fotografia;
    /**
     * Creates new form Principal
     */
    public Inicio() {
        initComponents();
        initStyles();
        initContenido();
        this.setLocationRelativeTo(null);
        this.setVisible(true);  
        setLogo("src/main/java/imagenes/LOGOREDSGN.png");
    }

    private void initStyles(){
        //inicializar fuentes
        mensaje.putClientProperty( "FlatLaf.style", "font: $h1.font" );
    }
    
    private void initContenido() {
        Principal p1 = new Principal();
        p1.setSize(800, 490);
        p1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    
    public void setLogo(String fotografia) { 
        this.fotografia = fotografia;
        try {
            logo.setSize(112, 112);
            ImageIcon imagen = new ImageIcon(fotografia);
            //Se redimensiona
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(logo.getWidth(),logo.getHeight(), 1));
            logo.setIcon(imgRedimensionada);            
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }
        
    /**
     * método para cambiar el contenido del panel "contenido" desde otras clases
     * @param nuevoContenido 
     */
    public void cambiarContenido(JPanel nuevoContenido) {
        contenido.removeAll();
        contenido.add(nuevoContenido, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BotonPrincipal = new javax.swing.JButton();
        BotonAlta = new javax.swing.JButton();
        BotonPedididosP = new javax.swing.JButton();
        BotonFidelizacion = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonConsulta = new javax.swing.JButton();
        BotonInforme = new javax.swing.JButton();
        cabecera = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1064, 640));

        menu.setBackground(new java.awt.Color(94, 57, 21));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        BotonPrincipal.setBackground(new java.awt.Color(94, 57, 21));
        BotonPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BotonPrincipal.setText("Principal");
        BotonPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonPrincipal.setBorderPainted(false);
        BotonPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrincipalActionPerformed(evt);
            }
        });

        BotonAlta.setBackground(new java.awt.Color(94, 57, 21));
        BotonAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonAlta.setForeground(new java.awt.Color(255, 255, 255));
        BotonAlta.setText("Dar de Alta");
        BotonAlta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonAlta.setBorderPainted(false);
        BotonAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });

        BotonPedididosP.setBackground(new java.awt.Color(94, 57, 21));
        BotonPedididosP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonPedididosP.setForeground(new java.awt.Color(255, 255, 255));
        BotonPedididosP.setText("Pedidos Pendientes");
        BotonPedididosP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonPedididosP.setBorderPainted(false);
        BotonPedididosP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPedididosP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonPedididosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedididosPActionPerformed(evt);
            }
        });

        BotonFidelizacion.setBackground(new java.awt.Color(94, 57, 21));
        BotonFidelizacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonFidelizacion.setForeground(new java.awt.Color(255, 255, 255));
        BotonFidelizacion.setText("Programa de fidelización");
        BotonFidelizacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonFidelizacion.setBorderPainted(false);
        BotonFidelizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFidelizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonFidelizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFidelizacionActionPerformed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(94, 57, 21));
        BotonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Cerrar/Salir");
        BotonSalir.setBorder(null);
        BotonSalir.setBorderPainted(false);
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonConsulta.setBackground(new java.awt.Color(94, 57, 21));
        BotonConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsulta.setText("Consultas");
        BotonConsulta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonConsulta.setBorderPainted(false);
        BotonConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaActionPerformed(evt);
            }
        });

        BotonInforme.setBackground(new java.awt.Color(94, 57, 21));
        BotonInforme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonInforme.setForeground(new java.awt.Color(255, 255, 255));
        BotonInforme.setText("Informes");
        BotonInforme.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BotonInforme.setBorderPainted(false);
        BotonInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInforme.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonPedididosP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonFidelizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonPedididosP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonFidelizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cabecera.setBackground(new java.awt.Color(150, 116, 83));
        cabecera.setPreferredSize(new java.awt.Dimension(794, 150));

        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("Bienvenido a TiendaLibros");

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(403, 403, 403))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                        .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        InicioSesionAlta isa = new InicioSesionAlta();
        isa.setSize(800, 490);
        isa.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(isa, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonFidelizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFidelizacionActionPerformed
        Fidelizacion f1 = new Fidelizacion();
        f1.setSize(800, 490);
        f1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(f1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonFidelizacionActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonPedididosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedididosPActionPerformed
        PedidosPendientes p1 = new PedidosPendientes();
        p1.setSize(800, 490);
        p1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonPedididosPActionPerformed

    private void BotonPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrincipalActionPerformed
        Principal p1 = new Principal();
        p1.setSize(800, 490);
        p1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonPrincipalActionPerformed

    private void BotonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaActionPerformed
        Object[] options = {"cliente", "libro", "cancelar"};
        int seleccion = JOptionPane.showOptionDialog(
            this, // Componente padre (en este caso, el formulario actual)
            "¿De qué desea consultar en histórico?",
            "Selección de Ventana",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, 
            options, 
            options[0]);

        
    if (seleccion == 0) {
        ConsultaCliente cc = new ConsultaCliente();
        cc.setSize(800, 490);
        cc.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(cc, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
    } else if (seleccion == 1) {
        ConsultaLibro cl = new ConsultaLibro();
        cl.setSize(800, 490);
        cl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(cl, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    }//GEN-LAST:event_BotonConsultaActionPerformed

    private void BotonInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInformeActionPerformed
        InicioSesionInformes isi = new InicioSesionInformes();
        isi.setSize(800, 490);
        isi.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(isi, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_BotonInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonConsulta;
    private javax.swing.JButton BotonFidelizacion;
    private javax.swing.JButton BotonInforme;
    private javax.swing.JButton BotonPedididosP;
    private javax.swing.JButton BotonPrincipal;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
