/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import codigo.Cliente;
import codigo.Domicilio;
import codigo.Libro;
import codigo.Pedido;
import codigo.UtilTienda;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import presentacion.Inicio;


/**
 *
 * @author giise
 */
public class GenerarPedido extends javax.swing.JPanel {
    
    private ArrayList<Libro> librosPedidos = new ArrayList();
    Domicilio domicilio = new Domicilio("","","",0,0);
    
    public GenerarPedido() {
        initComponents();
        initStyles();
        Tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        IniciarTabla();
    }

    public void initStyles(){
        Titulo.putClientProperty( "FlatLaf.style", "font: $h1.font" );
        BotonGenerarFactura.putClientProperty( "JButton.buttonType", "roundRect" );
        BotonPedidoPendiente.putClientProperty("JButton.buttonType", "roundRect" );
    }
    
    ArrayList<Libro> listaLibros;
    
    public void IniciarTabla(){
        DefaultTableModel d = new DefaultTableModel();
        Tabla.setModel(d);
        Object[] datos = new Object[2];
        String[] cabecera;
        cabecera = new String[] {"Titulo", "Codigo"};
        d.setColumnIdentifiers(cabecera);
        listaLibros = UtilTienda.getListaLibros();
 
        for(Libro libro : listaLibros) {
            datos[0] = libro.getTitulo();     
            datos[1] = libro.getCodigoL();
            d.addRow(datos);
        }
    }
    
    public void establecerDomicilio(Domicilio domicilio) {
    this.domicilio = domicilio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        CodigoPedido = new javax.swing.JTextField();
        jLabeldni = new javax.swing.JLabel();
        dniCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonSeleccionar = new javax.swing.JButton();
        BotonGenerarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        BotonDireccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ejemplares = new javax.swing.JFormattedTextField();
        BotonPedidoPendiente = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setForeground(new java.awt.Color(94, 57, 21));
        Titulo.setText("Introduzca todos los datos solicitados para realizar el pedido");

        jLabelCodigo.setText("Codigo de pedido:");

        jLabeldni.setText("DNI del cliente");

        jLabel1.setText("Busque los libros en la tabla, seleccionelos y pulse el botón:");

        BotonSeleccionar.setText("Seleccionar");
        BotonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionarActionPerformed(evt);
            }
        });

        BotonGenerarFactura.setBackground(new java.awt.Color(150, 116, 83));
        BotonGenerarFactura.setForeground(new java.awt.Color(255, 255, 255));
        BotonGenerarFactura.setText("Generar factura");
        BotonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarFacturaActionPerformed(evt);
            }
        });

        Tabla.setAutoCreateRowSorter(true);
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título", "Código"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jLabel2.setText("Nombre del cliente:");

        BotonDireccion.setText("Añadir dirección");
        BotonDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDireccionActionPerformed(evt);
            }
        });

        jLabel3.setText("ID del cliente:");

        jLabel4.setText("Ejemplares:");

        BotonPedidoPendiente.setBackground(new java.awt.Color(150, 116, 83));
        BotonPedidoPendiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonPedidoPendiente.setText("Generar pedido pendiente");
        BotonPedidoPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidoPendienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(BotonGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonPedidoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Titulo)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ejemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoPedido)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonDireccion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                .addComponent(jLabeldni)
                                .addGap(18, 18, 18)
                                .addComponent(dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(73, 73, 73))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Titulo)
                .addGap(28, 28, 28)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(CodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldni)
                    .addComponent(dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDireccion)
                    .addComponent(jLabel3)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BotonSeleccionar)
                    .addComponent(jLabel4)
                    .addComponent(Ejemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGenerarFactura)
                    .addComponent(BotonPedidoPendiente))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionarActionPerformed
        int seleccionado = Tabla.getSelectedRow();
        long codigo = listaLibros.get(seleccionado).getCodigoL();
        String autor = listaLibros.get(seleccionado).getAutor();
        String titulo = listaLibros.get(seleccionado).getTitulo();
        int ejemplares;
        
        if(Ejemplares.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe añadir la cantidad de ejemplares que desea del libro");
        }else if((Integer.parseInt(Ejemplares.getText())) > (listaLibros.get(seleccionado).getStock())){
            JOptionPane.showMessageDialog(this, "No hay tantos ejemplares en stock, debe generar un pedido pendiente");
            BotonGenerarFactura.setEnabled(false);
        }else{
            ejemplares = Integer.parseInt(Ejemplares.getText()); 
            Libro libroSeleccionado = new Libro(codigo,autor,titulo,ejemplares); 
            int ejemplaresAntes = listaLibros.get(seleccionado).getStock();
            listaLibros.get(seleccionado).setStock(ejemplaresAntes - ejemplares);
            librosPedidos.add(libroSeleccionado);
        }
  
    }//GEN-LAST:event_BotonSeleccionarActionPerformed

    private void BotonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarFacturaActionPerformed
        //generar factura y si sale bien:
        Cliente cliente = new Cliente(Id.getText(),dniCliente.getText(), Nombre.getText(), domicilio);
        LocalDate fecha = LocalDate.now();
        
        Pedido pedido = new Pedido(cliente, fecha, librosPedidos);
        UtilTienda.getListaPedidos().add(pedido);
        
        JOptionPane.showMessageDialog(GenerarPedido.this, "La factura se realizó correctamente", "", JOptionPane.INFORMATION_MESSAGE);
        
        Principal p1 = new Principal();
        p1.setSize(800,490);
        p1.setLocation(0,0);
        
        Inicio inicio = (Inicio) SwingUtilities.getWindowAncestor(this);
        inicio.cambiarContenido(p1);
    }//GEN-LAST:event_BotonGenerarFacturaActionPerformed

    private void BotonDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDireccionActionPerformed
        Direccion d = new Direccion(this);
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_BotonDireccionActionPerformed

    private void BotonPedidoPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidoPendienteActionPerformed
        Cliente cliente = new Cliente(Id.getText(),dniCliente.getText(), Nombre.getText(), domicilio);
        LocalDate fecha = LocalDate.now();
        
        Pedido pedido = new Pedido(cliente, fecha, librosPedidos);
        UtilTienda.getListaPedidosPendientes().add(pedido);
        
        Principal p2 = new Principal();
        p2.setSize(800,490);
        p2.setLocation(0,0);
        
        Inicio inicio = (Inicio) SwingUtilities.getWindowAncestor(this);
        inicio.cambiarContenido(p2);  
    }//GEN-LAST:event_BotonPedidoPendienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDireccion;
    private javax.swing.JButton BotonGenerarFactura;
    private javax.swing.JButton BotonPedidoPendiente;
    private javax.swing.JButton BotonSeleccionar;
    private javax.swing.JTextField CodigoPedido;
    private javax.swing.JFormattedTextField Ejemplares;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField dniCliente;
    private javax.swing.JPanel fondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabeldni;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
